dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run -m unittest discover -s tests/
  - coverage report