dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
matrix:
  allow_failures:
    - python: "3.8-dev"
install:
  - if [ "TRAVIS_PYTHON_VERSION" = "3.8-dev" ]; sudo apt-get install gcc gfortran python-dev libopenblas-dev liblapack-dev cython; fi;
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - coveralls