dist: xenial   # required for Python >= 3.7
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: "3.8-dev"
      addons:
        apt:
          packages:
            - gcc
            - gfortran
            - python-dev
            - libopenblas-dev
            - liblapack-dev
            - cython
  allow_failures:
    - python: "3.8-dev"
  fast_finish: true

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run -m unittest discover -s tests/
after_success:
  - coveralls